import React, { useEffect, useMemo, useState } from "react";
import {
  Bot,
  Box,
  Check,
  ChevronRight,
  ClipboardList,
  Download,
  FileArchive,
  FileText,
  Image,
  Layers3,
  Loader2,
  Lock,
  MessageSquareText,
  Paintbrush,
  Plus,
  Save,
  Settings,
  ShieldAlert,
  Sparkles,
  TableProperties,
  Upload,
  Wand2,
} from "lucide-react";
import { motion } from "motion/react";
import { saveAs } from "file-saver";
import {
  buildSm8f,
  checkAdminAccess,
  getAiStatus,
  loadCodexResponse,
  requestFormPlan,
  reviseFormPlan,
} from "./services/codexGeneratorService";
import {
  AiPlanResponse,
  AttachmentPayload,
  ChatMessage,
  DesignSettings,
  FieldCondition,
  FormSpec,
  GenerationState,
  ProjectRecord,
  ServiceM8Field,
  ToolMode,
} from "./types";
import { cn } from "./lib/utils";

const tools: { id: ToolMode; label: string; icon: React.ElementType; status: string }[] = [
  { id: "create_sm8f", label: "Create SM8F", icon: FileArchive, status: "Live" },
  { id: "update_sm8f", label: "Update SM8F", icon: ClipboardList, status: "Preview" },
  { id: "swms_builder", label: "SWMS Builder", icon: ShieldAlert, status: "Preview" },
];

const defaultDesign: DesignSettings = {
  companyName: "Autoform Studio",
  primaryColor: "#111827",
  accentColor: "#9fdb1d",
  headerColor: "#3f3f46",
  footerColor: "#111827",
  tableHeaderColor: "#3f3f46",
  tableBorderColor: "#d4d4d8",
  fontFamily: "Arial",
  bodyFontSize: 9,
  headingStyle: "bar",
  tableStyle: "source",
  logoPlacement: "left",
  logoWidth: 150,
  pageMargin: 720,
  headerText: "Generated ServiceM8 Form",
  footerText: "Commercial-in-confidence",
};
const STORAGE_KEY = "autoform_projects_v3";

const starterSpec: FormSpec = {
  title: "Untitled ServiceM8 Form",
  badgeName: "AUTOFORM",
  description: "Draft form generated by Autoform.",
  fields: [],
  docxContent: { style: "sourcePdfReplica", sections: [] },
  designSettings: defaultDesign,
};

function uid(prefix = "id") {
  return `${prefix}_${crypto.randomUUID()}`;
}

function cleanBadge(value: string) {
  return value.replace(/[^a-zA-Z0-9\s]/g, " ").replace(/\s+/g, " ").trim().slice(0, 11);
}

function emptyProject(mode: ToolMode = "create_sm8f"): ProjectRecord {
  return {
    id: uid("project"),
    title: "New Autoform request",
    mode,
    updatedAt: new Date().toISOString(),
    messages: [
      {
        id: uid("msg"),
        role: "assistant",
        content: "Tell me what ServiceM8 asset you need and upload any reference files. In local Codex mode I will prepare a handoff brief; with backend AI configured I will draft the form plan here.",
        timestamp: new Date().toISOString(),
      },
    ],
    spec: starterSpec,
    state: "idle",
    designSettings: defaultDesign,
  };
}

function loadProjects(): ProjectRecord[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [emptyProject()];
    const parsed = JSON.parse(raw) as ProjectRecord[];
    return parsed.length ? parsed : [emptyProject()];
  } catch {
    return [emptyProject()];
  }
}

function fileToAttachment(file: File): Promise<AttachmentPayload> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      resolve({
        id: uid("file"),
        name: file.name,
        mimeType: file.type || "application/octet-stream",
        size: file.size,
        data: String(reader.result).split(",")[1] || "",
      });
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function summarizePlan(plan: AiPlanResponse) {
  const questions = plan.clarificationQuestions.length
    ? `\n\nQuestions:\n${plan.clarificationQuestions.map((q) => `- ${q}`).join("\n")}`
    : "";
  return `${plan.summary}\n\nAssumptions:\n${plan.assumptions.map((a) => `- ${a}`).join("\n")}${questions}`;
}

export default function App() {
  const [projects, setProjects] = useState<ProjectRecord[]>(loadProjects);
  const [activeProjectId, setActiveProjectId] = useState(projects[0]?.id);
  const [activeSection, setActiveSection] = useState<"workspace" | "design" | "projects" | "settings">("workspace");
  const [prompt, setPrompt] = useState("");
  const [attachments, setAttachments] = useState<AttachmentPayload[]>([]);
  const [isWorking, setIsWorking] = useState(false);
  const [hasOpenAiKey, setHasOpenAiKey] = useState(false);
  const [accessGranted, setAccessGranted] = useState(() => localStorage.getItem("autoform_access") === "ok");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const project = projects.find((item) => item.id === activeProjectId) || projects[0];
  const spec = project.spec || starterSpec;

  const persist = (next: ProjectRecord[]) => {
    setProjects(next);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
  };

  useEffect(() => {
    getAiStatus()
      .then((status) => setHasOpenAiKey(status.hasOpenAiKey))
      .catch(() => setHasOpenAiKey(false));
  }, []);

  const updateProject = (patch: Partial<ProjectRecord>) => {
    const next = projects.map((item) =>
      item.id === project.id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item,
    );
    persist(next);
  };

  const fieldCounts = useMemo(() => {
    const fields = spec.fields || [];
    return {
      total: fields.length,
      required: fields.filter((field) => field.required).length,
      conditional: fields.filter((field) => field.conditions?.length).length,
      photos: fields.filter((field) => field.type === "photo").length,
    };
  }, [spec.fields]);

  const handleAccess = async (event: React.FormEvent) => {
    event.preventDefault();
    setError("");
    try {
      const ok = await checkAdminAccess(password);
      if (!ok) throw new Error("Incorrect app password.");
      localStorage.setItem("autoform_access", "ok");
      setAccessGranted(true);
    } catch (err: any) {
      setError(err.message || "Access failed.");
    }
  };

  const handleFiles = async (files: FileList | null) => {
    if (!files?.length) return;
    const loaded = await Promise.all(Array.from(files).map(fileToAttachment));
    setAttachments((current) => [...current, ...loaded]);
  };

  const applyPlan = (plan: AiPlanResponse, baseMessages = project.messages, state: GenerationState = "draft") => {
    const message: ChatMessage = {
      id: uid("msg"),
      role: "assistant",
      content: summarizePlan(plan),
      timestamp: new Date().toISOString(),
    };
    updateProject({
      title: plan.spec.title || project.title,
      spec: { ...plan.spec, designSettings: project.designSettings },
      messages: [...baseMessages, message],
      state: plan.clarificationQuestions.length ? "needsClarification" : state,
    });
  };

  const handleGenerate = async () => {
    if (!prompt.trim() && !attachments.length) return;
    setIsWorking(true);
    setError("");
    const userMessage: ChatMessage = {
      id: uid("msg"),
      role: "user",
      content: prompt || "Please inspect the attached files and draft the ServiceM8 form plan.",
      timestamp: new Date().toISOString(),
      attachments,
    };
    const baseMessages = [...project.messages, userMessage];
    updateProject({ messages: baseMessages, state: "draft" });
    try {
      const plan = spec.fields.length
        ? await reviseFormPlan({ prompt, mode: project.mode, currentSpec: spec, designSettings: project.designSettings })
        : await requestFormPlan({ prompt, mode: project.mode, attachments, designSettings: project.designSettings });
      applyPlan(plan, baseMessages);
      setPrompt("");
      setAttachments([]);
    } catch (err: any) {
      if (err.codexBrief) {
        const assistantMessage: ChatMessage = {
          id: uid("msg"),
          role: "assistant",
          content: `${err.message}\n\nA local bridge request has been written for Codex.\nRequest: ${err.requestPath || "not available"}\nResponse target: ${err.responsePath || "not available"}\n\n${err.codexBrief}`,
          timestamp: new Date().toISOString(),
        };
        updateProject({
          messages: [...baseMessages, assistantMessage],
          state: "needsClarification",
          codexRequestId: err.requestId,
          codexRequestPath: err.requestPath,
          codexResponsePath: err.responsePath,
        });
        setPrompt("");
        setAttachments([]);
      } else {
        setError(err.message || "AI generation failed.");
        updateProject({ state: "error" });
      }
    } finally {
      setIsWorking(false);
    }
  };

  const handleLoadCodexResponse = async () => {
    if (!project.codexRequestId) return;
    setIsWorking(true);
    setError("");
    try {
      const plan = await loadCodexResponse(project.codexRequestId);
      applyPlan(plan, project.messages, "draft");
      updateProject({ codexRequestId: undefined, codexRequestPath: undefined, codexResponsePath: undefined });
    } catch (err: any) {
      setError(err.message || "Codex response is not ready yet.");
    } finally {
      setIsWorking(false);
    }
  };

  const handleBuild = async () => {
    setIsWorking(true);
    setError("");
    updateProject({ state: "building" });
    try {
      const blob = await buildSm8f({ ...spec, designSettings: project.designSettings });
      saveAs(blob, `${spec.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "autoform"}.sm8f`);
      updateProject({ state: "ready" });
    } catch (err: any) {
      setError(err.message || "SM8F build failed.");
      updateProject({ state: "error" });
    } finally {
      setIsWorking(false);
    }
  };

  const setMode = (mode: ToolMode) => {
    updateProject({ mode });
    setActiveSection("workspace");
  };

  const addProject = () => {
    const nextProject = emptyProject("create_sm8f");
    persist([nextProject, ...projects]);
    setActiveProjectId(nextProject.id);
    setActiveSection("workspace");
  };

  const updateSpec = (nextSpec: FormSpec) => updateProject({ spec: { ...nextSpec, designSettings: project.designSettings } });
  const updateDesign = (nextDesign: DesignSettings) => updateProject({ designSettings: nextDesign, spec: { ...spec, designSettings: nextDesign } });

  if (!accessGranted) {
    return (
      <main className="min-h-screen bg-[#f6f7f3] text-zinc-950 flex items-center justify-center p-6">
        <form onSubmit={handleAccess} className="w-full max-w-md bg-white border border-zinc-200 rounded-[8px] shadow-2xl shadow-zinc-200/70 p-8">
          <div className="h-12 w-12 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center mb-6">
            <Lock size={22} />
          </div>
          <h1 className="text-3xl font-semibold tracking-tight">Autoform private studio</h1>
          <p className="text-sm text-zinc-500 mt-2">Enter the app password to manage ServiceM8 form assets.</p>
          <input
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            type="password"
            className="mt-6 w-full border border-zinc-300 rounded-[8px] px-3 py-3 text-sm outline-none focus:border-zinc-950"
            placeholder="App password"
          />
          {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
          <button className="mt-5 w-full bg-zinc-950 text-white rounded-[8px] py-3 text-sm font-semibold">Enter studio</button>
        </form>
      </main>
    );
  }

  return (
    <div className="min-h-screen bg-[#f6f7f3] text-zinc-950">
      <aside className="lg:fixed lg:inset-y-0 lg:left-0 lg:w-72 bg-[#111313] text-white border-r border-zinc-800 flex flex-col">
        <div className="p-5 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-[8px] bg-lime-300 text-zinc-950 flex items-center justify-center">
              <Wand2 size={22} />
            </div>
            <div>
              <p className="text-lg font-semibold">Autoform</p>
              <p className="text-xs text-zinc-400">ServiceM8 asset studio</p>
            </div>
          </div>
        </div>

        <div className="p-3">
          <p className="px-3 py-2 text-[11px] uppercase tracking-[0.18em] text-zinc-500">Tools</p>
          {tools.map((tool) => (
            <button
              key={tool.id}
              onClick={() => setMode(tool.id)}
              className={cn(
                "w-full flex items-center gap-3 px-3 py-3 rounded-[8px] text-left text-sm transition",
                project.mode === tool.id && activeSection === "workspace"
                  ? "bg-white text-zinc-950"
                  : "text-zinc-300 hover:bg-white/10",
              )}
            >
              <tool.icon size={18} />
              <span className="flex-1">{tool.label}</span>
              <span className="text-[10px] rounded px-1.5 py-0.5 bg-lime-300/15 text-lime-200">{tool.status}</span>
            </button>
          ))}
        </div>

        <div className="p-3 border-t border-white/10">
          {[
            ["design", Paintbrush, "Design Studio"],
            ["projects", Layers3, "Projects"],
            ["settings", Settings, "Settings"],
          ].map(([id, Icon, label]) => (
            <button
              key={String(id)}
              onClick={() => setActiveSection(id as any)}
              className={cn(
                "w-full flex items-center gap-3 px-3 py-3 rounded-[8px] text-left text-sm transition",
                activeSection === id ? "bg-lime-300 text-zinc-950" : "text-zinc-300 hover:bg-white/10",
              )}
            >
              <Icon size={18} />
              {label}
            </button>
          ))}
        </div>

        <div className="mt-auto p-4 border-t border-white/10">
          <button onClick={addProject} className="w-full flex items-center justify-center gap-2 bg-white text-zinc-950 rounded-[8px] py-2.5 text-sm font-semibold">
            <Plus size={16} />
            New request
          </button>
        </div>
      </aside>

      <main className="lg:pl-72">
        <header className="min-h-20 bg-[#f6f7f3]/90 backdrop-blur border-b border-zinc-200 sticky top-0 z-20 px-4 lg:px-8 py-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-zinc-500">{tools.find((tool) => tool.id === project.mode)?.label}</p>
            <h1 className="text-2xl font-semibold tracking-tight">{project.title}</h1>
          </div>
          <div className="flex items-center gap-3">
            <StatePill state={project.state} />
            <button onClick={handleBuild} disabled={!spec.fields.length || isWorking} className="flex items-center gap-2 bg-zinc-950 text-white rounded-[8px] px-4 py-2.5 text-sm font-semibold disabled:opacity-40">
              {isWorking && project.state === "building" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />}
              Generate SM8F
            </button>
          </div>
        </header>

        {activeSection === "workspace" && (
          <Workspace
            project={project}
            spec={spec}
            prompt={prompt}
            setPrompt={setPrompt}
            attachments={attachments}
            setAttachments={setAttachments}
            onFiles={handleFiles}
            onGenerate={handleGenerate}
            onLoadCodexResponse={handleLoadCodexResponse}
            onBuild={handleBuild}
            isWorking={isWorking}
            hasOpenAiKey={hasOpenAiKey}
            error={error}
            updateSpec={updateSpec}
            fieldCounts={fieldCounts}
          />
        )}
        {activeSection === "design" && (
          <DesignStudio
            design={project.designSettings}
            updateDesign={updateDesign}
            onLogo={async (files) => {
              const file = files?.[0];
              if (!file) return;
              const logo = await fileToAttachment(file);
              updateDesign({ ...project.designSettings, logo });
            }}
          />
        )}
        {activeSection === "projects" && <Projects projects={projects} activeProjectId={project.id} openProject={setActiveProjectId} />}
        {activeSection === "settings" && <SettingsPanel />}
      </main>
    </div>
  );
}

function StatePill({ state }: { state: GenerationState }) {
  const labels: Record<GenerationState, string> = {
    idle: "Ready",
    draft: "Drafting",
    needsClarification: "Needs review",
    approved: "Approved",
    building: "Building",
    ready: "SM8F ready",
    error: "Error",
  };
  return <span className="rounded-full border border-zinc-300 bg-white px-3 py-1 text-xs font-semibold text-zinc-600">{labels[state]}</span>;
}

function Workspace(props: {
  project: ProjectRecord;
  spec: FormSpec;
  prompt: string;
  setPrompt: (value: string) => void;
  attachments: AttachmentPayload[];
  setAttachments: React.Dispatch<React.SetStateAction<AttachmentPayload[]>>;
  onFiles: (files: FileList | null) => void;
  onGenerate: () => void;
  onLoadCodexResponse: () => void;
  onBuild: () => void;
  isWorking: boolean;
  hasOpenAiKey: boolean;
  error: string;
  updateSpec: (spec: FormSpec) => void;
  fieldCounts: { total: number; required: number; conditional: number; photos: number };
}) {
  return (
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(360px,0.9fr)_minmax(560px,1.4fr)_360px] gap-5 p-4 lg:p-6">
      <section className="bg-white border border-zinc-200 rounded-[8px] min-h-[calc(100vh-7rem)] flex flex-col">
        <PanelTitle icon={MessageSquareText} title="AI chat" subtitle="Describe, revise, approve" />
        {!props.hasOpenAiKey && (
          <div className="mx-4 mt-4 rounded-[8px] border border-lime-200 bg-lime-50 p-3 text-sm text-zinc-700 space-y-2">
            <p>Codex local bridge is active. This app writes request files for Codex instead of generating fake AI fields.</p>
            {props.project.codexRequestId && (
              <div className="space-y-2">
                <p className="font-mono text-xs break-all">Response: {props.project.codexResponsePath}</p>
                <button onClick={props.onLoadCodexResponse} disabled={props.isWorking} className="rounded-[8px] bg-zinc-950 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">
                  Load Codex response
                </button>
              </div>
            )}
          </div>
        )}
        <div className="flex-1 overflow-auto px-4 space-y-4">
          {props.project.messages.map((message) => (
            <div key={message.id} className={cn("rounded-[8px] p-4 text-sm whitespace-pre-wrap", message.role === "user" ? "bg-zinc-950 text-white" : "bg-[#f4f5ef] text-zinc-800")}>
              <div className="flex items-center gap-2 mb-2 text-xs opacity-70">
                {message.role === "user" ? <MessageSquareText size={14} /> : <Bot size={14} />}
                {message.role}
              </div>
              {message.content}
              {!!message.attachments?.length && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {message.attachments.map((file) => (
                    <span key={file.id}>
                      <FileChip file={file} />
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="p-4 border-t border-zinc-200 space-y-3">
          <textarea
            value={props.prompt}
            onChange={(event) => props.setPrompt(event.target.value)}
            className="w-full h-28 resize-none rounded-[8px] border border-zinc-300 p-3 text-sm outline-none focus:border-zinc-950"
            placeholder="Ask Autoform to inspect a PDF, build a form, add conditional logic, or revise the current spec..."
          />
          <div className="flex flex-wrap gap-2">
            {props.attachments.map((file) => (
              <button key={file.id} onClick={() => props.setAttachments((current) => current.filter((item) => item.id !== file.id))}>
                <FileChip file={file} />
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 border border-zinc-300 rounded-[8px] px-3 py-2 text-sm cursor-pointer bg-white">
              <Upload size={16} />
              Upload files
              <input className="hidden" type="file" multiple accept=".pdf,.docx,.sm8f,.json,.png,.jpg,.jpeg,.txt,.md" onChange={(event) => props.onFiles(event.target.files)} />
            </label>
            <button onClick={props.onGenerate} disabled={props.isWorking || (!props.prompt.trim() && !props.attachments.length)} className="flex-1 bg-lime-300 text-zinc-950 rounded-[8px] px-4 py-2 text-sm font-semibold disabled:opacity-50">
              {props.isWorking ? "Working..." : props.hasOpenAiKey ? (props.spec.fields.length ? "Revise plan" : "Generate plan") : "Prepare Codex brief"}
            </button>
          </div>
          {props.error && <p className="text-sm text-red-600">{props.error}</p>}
        </div>
      </section>

      <section className="space-y-5">
        <Metrics counts={props.fieldCounts} />
        <SpecEditor spec={props.spec} updateSpec={props.updateSpec} />
      </section>

      <section className="space-y-5">
        <OutputPanel spec={props.spec} onBuild={props.onBuild} disabled={props.isWorking || !props.spec.fields.length} />
        <PreviewPanel spec={props.spec} />
      </section>
    </div>
  );
}

function PanelTitle({ icon: Icon, title, subtitle }: { icon: React.ElementType; title: string; subtitle: string }) {
  return (
    <div className="p-4 border-b border-zinc-200 flex items-center gap-3">
      <div className="h-9 w-9 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center">
        <Icon size={18} />
      </div>
      <div>
        <h2 className="font-semibold">{title}</h2>
        <p className="text-xs text-zinc-500">{subtitle}</p>
      </div>
    </div>
  );
}

function FileChip({ file }: { file: AttachmentPayload }) {
  return (
    <span className="inline-flex items-center gap-1 rounded-[6px] border border-zinc-300 bg-white px-2 py-1 text-xs text-zinc-700">
      <FileText size={13} />
      {file.name}
    </span>
  );
}

function Metrics({ counts }: { counts: { total: number; required: number; conditional: number; photos: number } }) {
  return (
    <div className="grid grid-cols-4 gap-3">
      {[
        ["Fields", counts.total],
        ["Required", counts.required],
        ["Logic", counts.conditional],
        ["Photos", counts.photos],
      ].map(([label, value]) => (
        <div key={label} className="bg-white border border-zinc-200 rounded-[8px] p-4">
          <p className="text-xs text-zinc-500">{label}</p>
          <p className="text-2xl font-semibold">{value}</p>
        </div>
      ))}
    </div>
  );
}

function SpecEditor({ spec, updateSpec }: { spec: FormSpec; updateSpec: (spec: FormSpec) => void }) {
  const updateField = (index: number, patch: Partial<ServiceM8Field>) => {
    const fields = spec.fields.map((field, fieldIndex) => (fieldIndex === index ? { ...field, ...patch } : field));
    updateSpec({ ...spec, fields });
  };

  const addField = () => {
    updateSpec({
      ...spec,
      fields: [
        ...spec.fields,
        { label: "New Question", type: "text", required: false, additionalDetails: "", sortOrder: spec.fields.length + 1 },
      ],
    });
  };

  return (
    <div className="bg-white border border-zinc-200 rounded-[8px] overflow-hidden">
      <PanelTitle icon={TableProperties} title="Editable form spec" subtitle="Fields, options, required states and skip logic" />
      <div className="p-4 grid grid-cols-3 gap-3 border-b border-zinc-200">
        <TextInput label="Title" value={spec.title} onChange={(title) => updateSpec({ ...spec, title })} />
        <TextInput label="Badge" value={spec.badgeName} onChange={(badgeName) => updateSpec({ ...spec, badgeName: cleanBadge(badgeName) })} />
        <TextInput label="Description" value={spec.description} onChange={(description) => updateSpec({ ...spec, description })} />
      </div>
      <div className="overflow-auto max-h-[56vh]">
        <table className="w-full text-sm">
          <thead className="sticky top-0 bg-zinc-950 text-white">
            <tr>
              <th className="text-left p-2 font-medium">Question</th>
              <th className="text-left p-2 font-medium">Type</th>
              <th className="text-left p-2 font-medium">Options</th>
              <th className="text-left p-2 font-medium">Req</th>
              <th className="text-left p-2 font-medium">Condition</th>
            </tr>
          </thead>
          <tbody>
            {spec.fields.map((field, index) => (
              <tr key={`${field.label}-${index}`} className="border-b border-zinc-200 align-top">
                <td className="p-2 min-w-56">
                  <input className="w-full rounded border border-zinc-200 px-2 py-1" value={field.label} onChange={(event) => updateField(index, { label: event.target.value })} />
                  <input className="mt-1 w-full rounded border border-zinc-200 px-2 py-1 text-xs" placeholder="Guidance" value={field.additionalDetails || ""} onChange={(event) => updateField(index, { additionalDetails: event.target.value })} />
                </td>
                <td className="p-2">
                  <select className="rounded border border-zinc-200 px-2 py-1" value={field.type} onChange={(event) => updateField(index, { type: event.target.value as ServiceM8Field["type"] })}>
                    {["text", "textarea", "number", "date", "time", "select", "checkbox", "multi_answer", "photo", "signature"].map((type) => <option key={type}>{type}</option>)}
                  </select>
                </td>
                <td className="p-2 min-w-44">
                  <input className="w-full rounded border border-zinc-200 px-2 py-1 text-xs" value={(field.options || []).join(", ")} onChange={(event) => updateField(index, { options: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} />
                </td>
                <td className="p-2">
                  <input type="checkbox" checked={field.required} onChange={(event) => updateField(index, { required: event.target.checked })} />
                </td>
                <td className="p-2 min-w-64">
                  <ConditionEditor condition={field.conditions?.[0]} onChange={(condition) => updateField(index, { conditions: condition.questionLabel ? [condition] : [] })} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <button onClick={addField} className="m-4 flex items-center gap-2 rounded-[8px] border border-zinc-300 px-3 py-2 text-sm">
        <Plus size={16} />
        Add field
      </button>
    </div>
  );
}

function ConditionEditor({ condition, onChange }: { condition?: FieldCondition; onChange: (condition: FieldCondition) => void }) {
  const value = condition || { questionLabel: "", operator: "EQ", value: "" };
  return (
    <div className="grid grid-cols-[1fr_80px_1fr] gap-1">
      <input className="rounded border border-zinc-200 px-2 py-1 text-xs" placeholder="Question" value={value.questionLabel} onChange={(event) => onChange({ ...value, questionLabel: event.target.value })} />
      <select className="rounded border border-zinc-200 px-1 py-1 text-xs" value={value.operator} onChange={(event) => onChange({ ...value, operator: event.target.value as FieldCondition["operator"] })}>
        {["EQ", "NEQ", "CON", "NCON"].map((operator) => <option key={operator}>{operator}</option>)}
      </select>
      <input className="rounded border border-zinc-200 px-2 py-1 text-xs" placeholder="Value" value={value.value} onChange={(event) => onChange({ ...value, value: event.target.value })} />
    </div>
  );
}

function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}
      <input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-[8px] border border-zinc-300 px-3 py-2 text-sm text-zinc-900" />
    </label>
  );
}

function OutputPanel({ spec, onBuild, disabled }: { spec: FormSpec; onBuild: () => void; disabled: boolean }) {
  return (
    <div className="bg-zinc-950 text-white rounded-[8px] p-5">
      <div className="flex items-center gap-3">
        <Box className="text-lime-300" />
        <div>
          <h2 className="font-semibold">SM8F package</h2>
          <p className="text-xs text-zinc-400">ZIP archive with form.json and template.docx</p>
        </div>
      </div>
      <button onClick={onBuild} disabled={disabled} className="mt-5 w-full bg-lime-300 text-zinc-950 rounded-[8px] py-3 text-sm font-semibold disabled:opacity-40">
        Build downloadable .sm8f
      </button>
      <p className="mt-4 text-xs text-zinc-400">Badge: {spec.badgeName || "Unset"} · Fields: {spec.fields.length}</p>
    </div>
  );
}

function PreviewPanel({ spec }: { spec: FormSpec }) {
  return (
    <div className="bg-white border border-zinc-200 rounded-[8px] p-4">
      <PanelTitle icon={FileText} title="Report preview" subtitle="Structure and document sections" />
      <div className="mt-4 space-y-3 max-h-[52vh] overflow-auto">
        {spec.docxContent.sections.length ? spec.docxContent.sections.map((section) => (
          <div key={section.title} className="border border-zinc-200 rounded-[8px] overflow-hidden">
            <div className="bg-zinc-800 text-white px-3 py-2 text-sm font-semibold">{section.title}</div>
            <pre className="p-3 text-xs whitespace-pre-wrap font-sans text-zinc-600">{section.content || "No content yet"}</pre>
          </div>
        )) : <p className="text-sm text-zinc-500">Generate a plan to preview DOCX sections.</p>}
      </div>
    </div>
  );
}

function DesignStudio({ design, updateDesign, onLogo }: { design: DesignSettings; updateDesign: (design: DesignSettings) => void; onLogo: (files: FileList | null) => void }) {
  const update = (patch: Partial<DesignSettings>) => updateDesign({ ...design, ...patch });
  return (
    <div className="p-4 lg:p-6 grid grid-cols-1 xl:grid-cols-[1fr_420px] gap-6">
      <section className="bg-white border border-zinc-200 rounded-[8px] p-6">
        <PanelTitle icon={Paintbrush} title="Full style editor" subtitle="Brand, typography, table and document controls" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
          <TextInput label="Company name" value={design.companyName} onChange={(companyName) => update({ companyName })} />
          <TextInput label="Header text" value={design.headerText} onChange={(headerText) => update({ headerText })} />
          <TextInput label="Footer text" value={design.footerText} onChange={(footerText) => update({ footerText })} />
          <label className="text-xs text-zinc-500">
            Logo upload
            <span className="mt-1 flex items-center gap-2 rounded-[8px] border border-dashed border-zinc-300 px-3 py-2 text-sm text-zinc-700 cursor-pointer">
              <Image size={16} />
              Upload logo
              <input className="hidden" type="file" accept=".png,.jpg,.jpeg" onChange={(event) => onLogo(event.target.files)} />
            </span>
            {design.logo && <span className="mt-1 block text-[11px] text-zinc-500">{design.logo.name}</span>}
          </label>
          {[
            ["Primary", "primaryColor"],
            ["Accent", "accentColor"],
            ["Header", "headerColor"],
            ["Footer", "footerColor"],
            ["Table header", "tableHeaderColor"],
            ["Table border", "tableBorderColor"],
          ].map(([label, key]) => (
            <label key={key} className="text-xs text-zinc-500">
              {label}
              <input type="color" value={(design as any)[key]} onChange={(event) => update({ [key]: event.target.value } as any)} className="mt-1 h-10 w-full rounded border border-zinc-300" />
            </label>
          ))}
          <Select label="Font" value={design.fontFamily} onChange={(fontFamily) => update({ fontFamily: fontFamily as DesignSettings["fontFamily"] })} options={["Arial", "Calibri", "Inter", "Aptos"]} />
          <Select label="Heading style" value={design.headingStyle} onChange={(headingStyle) => update({ headingStyle: headingStyle as DesignSettings["headingStyle"] })} options={["bar", "underline", "boxed"]} />
          <Select label="Table style" value={design.tableStyle} onChange={(tableStyle) => update({ tableStyle: tableStyle as DesignSettings["tableStyle"] })} options={["source", "minimal", "grid"]} />
          <Select label="Logo placement" value={design.logoPlacement} onChange={(logoPlacement) => update({ logoPlacement: logoPlacement as DesignSettings["logoPlacement"] })} options={["left", "center", "right"]} />
          <Range label="Body font size" value={design.bodyFontSize} min={8} max={14} onChange={(bodyFontSize) => update({ bodyFontSize })} />
          <Range label="Page margin" value={design.pageMargin} min={360} max={1440} onChange={(pageMargin) => update({ pageMargin })} />
          <Range label="Logo width" value={design.logoWidth} min={80} max={280} onChange={(logoWidth) => update({ logoWidth })} />
        </div>
      </section>
      <section className="rounded-[8px] border border-zinc-200 bg-white p-5">
        <div className="aspect-[3/4] bg-[#fbfbf8] border border-zinc-300 p-8 shadow-xl">
          <div style={{ background: design.headerColor }} className="h-14 text-white flex items-center px-4 font-semibold">
            {design.companyName}
          </div>
          <div className="mt-5" style={{ color: design.primaryColor }}>
            <h3 className="text-2xl font-semibold">Report heading</h3>
            <p className="mt-2 text-sm text-zinc-500">{design.headerText}</p>
          </div>
          <div className="mt-6 border" style={{ borderColor: design.tableBorderColor }}>
            <div className="px-3 py-2 text-white text-sm font-semibold" style={{ background: design.tableHeaderColor }}>Section</div>
            <div className="grid grid-cols-2 text-sm">
              <div className="p-3 border-r" style={{ borderColor: design.tableBorderColor }}>Question</div>
              <div className="p-3">Answer</div>
            </div>
          </div>
          <div className="mt-auto pt-10 text-xs" style={{ color: design.footerColor }}>{design.footerText}</div>
        </div>
      </section>
    </div>
  );
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}
      <select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-[8px] border border-zinc-300 px-3 py-2 text-sm text-zinc-900">
        {options.map((option) => <option key={option}>{option}</option>)}
      </select>
    </label>
  );
}

function Range({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}: {value}
      <input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full accent-lime-400" />
    </label>
  );
}

function Projects({ projects, activeProjectId, openProject }: { projects: ProjectRecord[]; activeProjectId: string; openProject: (id: string) => void }) {
  return (
    <div className="p-6">
      <div className="bg-white border border-zinc-200 rounded-[8px]">
        <PanelTitle icon={Layers3} title="Projects" subtitle="Local browser project history" />
        <div className="divide-y divide-zinc-200">
          {projects.map((project) => (
            <button key={project.id} onClick={() => openProject(project.id)} className={cn("w-full p-4 flex items-center justify-between text-left", activeProjectId === project.id && "bg-lime-50")}>
              <div>
                <p className="font-semibold">{project.title}</p>
                <p className="text-xs text-zinc-500">{project.mode} · {new Date(project.updatedAt).toLocaleString()}</p>
              </div>
              <ChevronRight size={18} />
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function SettingsPanel() {
  return (
    <div className="p-6">
      <div className="bg-white border border-zinc-200 rounded-[8px] p-6 max-w-2xl">
        <PanelTitle icon={Settings} title="Settings" subtitle="Environment and deployment checklist" />
        <div className="mt-6 space-y-3 text-sm text-zinc-600">
          <p><Check className="inline mr-2 text-lime-600" size={16} />Set `OPENAI_API_KEY` on the server or Vercel project.</p>
          <p><Check className="inline mr-2 text-lime-600" size={16} />Set `APP_PASSWORD` for private admin access.</p>
          <p><Sparkles className="inline mr-2 text-blue-600" size={16} />Uploaded files are session-only in V1; projects are stored in browser localStorage.</p>
        </div>
      </div>
    </div>
  );
}
