import React, { useEffect, useMemo, useState } from "react";
import {
  Bot,
  Box,
  Check,
  ChevronRight,
  ClipboardList,
  Download,
  FileArchive,
  FileText,
  GripVertical,
  Image,
  Layers3,
  Loader2,
  Lock,
  MessageSquareText,
  Paintbrush,
  Plus,
  Pencil,
  Save,
  Settings,
  ShieldAlert,
  Sparkles,
  TableProperties,
  Upload,
  Wand2,
  X,
} from "lucide-react";
import { motion } from "motion/react";
import { saveAs } from "file-saver";
import {
  buildSm8f,
  checkAdminAccess,
  getAiStatus,
  loadCodexResponse,
  loadProjectsFromDb,
  requestFormPlan,
  saveOpenAiKey,
  saveProjectsToDb,
  reviseFormPlan,
} from "./services/codexGeneratorService";
import {
  AiPlanResponse,
  AttachmentPayload,
  ChatMessage,
  DesignSettings,
  FieldCondition,
  FormSpec,
  GenerationState,
  ProjectRecord,
  ServiceM8Field,
  ToolMode,
} from "./types";
import { cn } from "./lib/utils";

const tools: { id: ToolMode; label: string; icon: React.ElementType; status: string }[] = [
  { id: "create_from_prompt", label: "Create New Form from AI Prompt", icon: MessageSquareText, status: "Live" },
  { id: "create_from_pdf", label: "Create from Existing PDF", icon: FileText, status: "Preview" },
  { id: "update_existing_form", label: "Update Existing Form", icon: ClipboardList, status: "Preview" },
  { id: "swms_builder", label: "SWMS Builder", icon: ShieldAlert, status: "Preview" },
];

const defaultDesign: DesignSettings = {
  companyName: "Autoform Studio",
  designBrief: "Clean trade-service report, mobile-friendly form, editable table-based PDF output.",
  aiChooseDesign: true,
  stylePreset: "ai",
  primaryColor: "#111827",
  accentColor: "#9fdb1d",
  headerColor: "#3f3f46",
  footerColor: "#111827",
  tableHeaderColor: "#3f3f46",
  tableBorderColor: "#d4d4d8",
  fontFamily: "Arial",
  bodyFontSize: 9,
  headingStyle: "bar",
  tableStyle: "source",
  logoPlacement: "left",
  logoWidth: 150,
  pageMargin: 720,
  headerText: "Generated ServiceM8 Form",
  footerText: "Commercial-in-confidence",
};
const STORAGE_KEY = "autoform_projects_v4";

const starterSpec: FormSpec = {
  title: "Untitled ServiceM8 Form",
  badgeName: "AUTOFORM",
  description: "Draft form generated by Autoform.",
  fields: [],
  docxContent: { style: "sourcePdfReplica", sections: [] },
  designSettings: defaultDesign,
};

function uid(prefix = "id") {
  return `${prefix}_${crypto.randomUUID()}`;
}

function cleanBadge(value: string) {
  return value.replace(/[^a-zA-Z0-9\s]/g, " ").replace(/\s+/g, " ").trim().slice(0, 11);
}

function emptyProject(mode: ToolMode = "create_from_prompt"): ProjectRecord {
  return {
    id: uid("project"),
    title: "New Autoform request",
    mode,
    updatedAt: new Date().toISOString(),
    messages: [
      {
        id: uid("msg"),
        role: "assistant",
        content: "Describe the form you need, choose any design direction, and I will return a build plan with the proposed questions, sections, logic and report layout before the SM8F is built.",
        timestamp: new Date().toISOString(),
      },
    ],
    spec: starterSpec,
    state: "idle",
    designSettings: defaultDesign,
  };
}

function loadProjects(): ProjectRecord[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [emptyProject()];
    const parsed = (JSON.parse(raw) as ProjectRecord[]).map((item) => ({
      ...item,
      spec: item.spec ? normalizeFormSpecLabels(item.spec) : item.spec,
    }));
    if (!parsed.length) return [emptyProject()];
    const promptIndex = parsed.findIndex((item) => item.mode === "create_from_prompt");
    if (promptIndex <= 0) return parsed;
    return [parsed[promptIndex], ...parsed.slice(0, promptIndex), ...parsed.slice(promptIndex + 1)];
  } catch {
    return [emptyProject()];
  }
}

function fileToAttachment(file: File): Promise<AttachmentPayload> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      resolve({
        id: uid("file"),
        name: file.name,
        mimeType: file.type || "application/octet-stream",
        size: file.size,
        data: String(reader.result).split(",")[1] || "",
      });
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function summarizePlan(plan: AiPlanResponse) {
  const questions = plan.clarificationQuestions.length
    ? `\n\nQuestions:\n${plan.clarificationQuestions.map((q) => `- ${q}`).join("\n")}`
    : "";
  return `${plan.summary}\n\nAssumptions:\n${plan.assumptions.map((a) => `- ${a}`).join("\n")}${questions}`;
}

function humanizeFieldLabel(value: string) {
  const raw = String(value || "").trim();
  if (!raw) return raw;
  if (/\s/.test(raw) && !raw.includes("_")) return raw;

  const words = raw
    .replace(/[_-]+/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/\s+/g, " ")
    .trim()
    .split(" ");

  const smallWords = new Set(["a", "an", "and", "as", "at", "by", "for", "from", "if", "in", "of", "on", "or", "the", "to", "with"]);
  const acronyms = new Set(["AC", "BMS", "DB", "ETA", "JSA", "LOTO", "RCD", "SCADA", "SM8F", "SWMS"]);

  return words
    .map((word, index) => {
      const upper = word.toUpperCase();
      const lower = word.toLowerCase();
      if (index === 0 && upper === "NO") return "No.";
      if (acronyms.has(upper)) return upper;
      if (index > 0 && smallWords.has(lower)) return lower;
      return `${word.charAt(0).toUpperCase()}${word.slice(1).toLowerCase()}`;
    })
    .join(" ");
}

function normalizeFormSpecLabels(spec: FormSpec): FormSpec {
  const labelMap = new Map<string, string>();
  const fields = (spec.fields || []).map((field) => {
    const label = humanizeFieldLabel(field.label);
    labelMap.set(field.label, label);
    labelMap.set(field.label.replace(/\s+/g, ""), label);
    return { ...field, label };
  });

  const normalizeCondition = (condition: FieldCondition): FieldCondition => {
    const questionLabel = labelMap.get(condition.questionLabel) || humanizeFieldLabel(condition.questionLabel);
    return { ...condition, questionLabel };
  };

  const normalizedFields = fields.map((field) => ({
    ...field,
    conditions: field.conditions?.map(normalizeCondition),
  }));

  const replaceLabels = (content: string) => {
    let next = content;
    for (const [from, to] of labelMap.entries()) {
      if (!from || from === to) continue;
      next = next.replace(new RegExp(from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g"), to);
    }
    return next;
  };

  return {
    ...spec,
    fields: normalizedFields,
    docxContent: {
      ...spec.docxContent,
      sections: (spec.docxContent?.sections || []).map((section) => ({
        ...section,
        content: replaceLabels(section.content || ""),
        conditions: section.conditions?.map(normalizeCondition),
        displayWhen: Array.isArray(section.displayWhen)
          ? section.displayWhen.map(normalizeCondition)
          : section.displayWhen
            ? normalizeCondition(section.displayWhen)
            : section.displayWhen,
      })),
    },
  };
}

export default function App() {
  const [projects, setProjects] = useState<ProjectRecord[]>(loadProjects);
  const [activeProjectId, setActiveProjectId] = useState(projects[0]?.id);
  const [activeSection, setActiveSection] = useState<"workspace" | "projects" | "settings">("workspace");
  const [prompt, setPrompt] = useState("");
  const [attachments, setAttachments] = useState<AttachmentPayload[]>([]);
  const [isWorking, setIsWorking] = useState(false);
  const [hasOpenAiKey, setHasOpenAiKey] = useState(false);
  const [showNewMenu, setShowNewMenu] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [showDesign, setShowDesign] = useState(false);
  const [accessGranted, setAccessGranted] = useState(() => localStorage.getItem("autoform_access") === "ok");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const project = projects.find((item) => item.id === activeProjectId) || projects[0];
  const spec = project.spec || starterSpec;

  const persist = (next: ProjectRecord[]) => {
    setProjects(next);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
    saveProjectsToDb(next).catch(() => undefined);
  };

  useEffect(() => {
    getAiStatus()
      .then((status) => setHasOpenAiKey(status.hasOpenAiKey))
      .catch(() => setHasOpenAiKey(false));
    loadProjectsFromDb()
      .then((dbProjects) => {
        if (dbProjects.length) {
          const normalizedProjects = dbProjects.map((item) => ({
            ...item,
            spec: item.spec ? normalizeFormSpecLabels(item.spec) : item.spec,
          }));
          setProjects(normalizedProjects);
          const promptProject = normalizedProjects.find((item) => item.mode === "create_from_prompt");
          setActiveProjectId((promptProject || dbProjects[0]).id);
          localStorage.setItem(STORAGE_KEY, JSON.stringify(normalizedProjects));
        }
      })
      .catch(() => undefined);
  }, []);

  const updateProject = (patch: Partial<ProjectRecord>) => {
    const next = projects.map((item) =>
      item.id === project.id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item,
    );
    persist(next);
  };

  const fieldCounts = useMemo(() => {
    const fields = spec.fields || [];
    return {
      total: fields.length,
      required: fields.filter((field) => field.required).length,
      conditional: fields.filter((field) => field.conditions?.length).length,
      photos: fields.filter((field) => field.type === "photo").length,
    };
  }, [spec.fields]);

  const handleAccess = async (event: React.FormEvent) => {
    event.preventDefault();
    setError("");
    try {
      const ok = await checkAdminAccess(password);
      if (!ok) throw new Error("Incorrect app password.");
      localStorage.setItem("autoform_access", "ok");
      setAccessGranted(true);
    } catch (err: any) {
      setError(err.message || "Access failed.");
    }
  };

  const handleFiles = async (files: FileList | null) => {
    if (!files?.length) return;
    const loaded = await Promise.all(Array.from(files).map(fileToAttachment));
    setAttachments((current) => [...current, ...loaded]);
  };

  const applyPlan = (plan: AiPlanResponse, baseMessages = project.messages, state: GenerationState = "draft") => {
    const normalizedSpec = normalizeFormSpecLabels(plan.spec);
    const message: ChatMessage = {
      id: uid("msg"),
      role: "assistant",
      content: summarizePlan(plan),
      timestamp: new Date().toISOString(),
    };
    updateProject({
      title: normalizedSpec.title || project.title,
      spec: { ...normalizedSpec, designSettings: { ...project.designSettings, ...(normalizedSpec.designSettings || {}) } },
      messages: [...baseMessages, message],
      state: plan.clarificationQuestions.length ? "needsClarification" : state,
    });
  };

  const handleGenerate = async () => {
    if (!prompt.trim() && !attachments.length) return;
    setIsWorking(true);
    setError("");
    const userMessage: ChatMessage = {
      id: uid("msg"),
      role: "user",
      content: prompt || "Please inspect the attached files and draft the ServiceM8 form plan.",
      timestamp: new Date().toISOString(),
      attachments,
    };
    const baseMessages = [...project.messages, userMessage];
    updateProject({ messages: baseMessages, state: "draft" });
    try {
      const plan = spec.fields.length
        ? await reviseFormPlan({ prompt, mode: project.mode, currentSpec: spec, designSettings: project.designSettings })
        : await requestFormPlan({ prompt, mode: project.mode, attachments, designSettings: project.designSettings });
      applyPlan(plan, baseMessages);
      setPrompt("");
      setAttachments([]);
    } catch (err: any) {
      if (err.codexBrief) {
        const assistantMessage: ChatMessage = {
          id: uid("msg"),
          role: "assistant",
          content: `${err.message}\n\nA local bridge request has been written for Codex.\nRequest: ${err.requestPath || "not available"}\nResponse target: ${err.responsePath || "not available"}\n\n${err.codexBrief}`,
          timestamp: new Date().toISOString(),
        };
        updateProject({
          messages: [...baseMessages, assistantMessage],
          state: "needsClarification",
          codexRequestId: err.requestId,
          codexRequestPath: err.requestPath,
          codexResponsePath: err.responsePath,
        });
        setPrompt("");
        setAttachments([]);
      } else {
        setError(err.message || "AI generation failed.");
        updateProject({ state: "error" });
      }
    } finally {
      setIsWorking(false);
    }
  };

  const handleLoadCodexResponse = async () => {
    if (!project.codexRequestId) return;
    setIsWorking(true);
    setError("");
    try {
      const plan = await loadCodexResponse(project.codexRequestId);
      applyPlan(plan, project.messages, "draft");
      updateProject({ codexRequestId: undefined, codexRequestPath: undefined, codexResponsePath: undefined });
    } catch (err: any) {
      setError(err.message || "Codex response is not ready yet.");
    } finally {
      setIsWorking(false);
    }
  };

  const handleBuild = async () => {
    setIsWorking(true);
    setError("");
    updateProject({ state: "building" });
    try {
      const normalizedSpec = normalizeFormSpecLabels(spec);
      const blob = await buildSm8f({ ...normalizedSpec, designSettings: project.designSettings });
      saveAs(blob, `${spec.title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "autoform"}.sm8f`);
      updateProject({ state: "ready" });
    } catch (err: any) {
      setError(err.message || "SM8F build failed.");
      updateProject({ state: "error" });
    } finally {
      setIsWorking(false);
    }
  };

  const setMode = (mode: ToolMode) => {
    updateProject({ mode });
    setActiveSection("workspace");
  };

  const addProject = () => {
    const nextProject = emptyProject("create_from_prompt");
    persist([nextProject, ...projects]);
    setActiveProjectId(nextProject.id);
    setActiveSection("workspace");
  };

  const addProjectWithMode = (mode: ToolMode) => {
    const nextProject = emptyProject(mode);
    persist([nextProject, ...projects]);
    setActiveProjectId(nextProject.id);
    setActiveSection("workspace");
    setShowNewMenu(false);
  };

  const updateSpec = (nextSpec: FormSpec) => updateProject({ spec: { ...normalizeFormSpecLabels(nextSpec), designSettings: project.designSettings } });
  const updateDesign = (nextDesign: DesignSettings) => updateProject({ designSettings: nextDesign, spec: { ...spec, designSettings: nextDesign } });

  if (!accessGranted) {
    return (
      <main className="min-h-screen bg-[#f6f7f3] text-zinc-950 flex items-center justify-center p-6">
        <form onSubmit={handleAccess} className="w-full max-w-md bg-white border border-zinc-200 rounded-[8px] shadow-2xl shadow-zinc-200/70 p-8">
          <div className="h-12 w-12 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center mb-6">
            <Lock size={22} />
          </div>
          <h1 className="text-3xl font-semibold tracking-tight">Autoform private studio</h1>
          <p className="text-sm text-zinc-500 mt-2">Enter the app password to manage ServiceM8 form assets.</p>
          <input
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            type="password"
            className="mt-6 w-full border border-zinc-300 rounded-[8px] px-3 py-3 text-sm outline-none focus:border-zinc-950"
            placeholder="App password"
          />
          {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
          <button className="mt-5 w-full bg-zinc-950 text-white rounded-[8px] py-3 text-sm font-semibold">Enter studio</button>
        </form>
      </main>
    );
  }

  return (
    <div className="min-h-screen bg-[#f6f7f3] text-zinc-950">
      <aside className="lg:fixed lg:inset-y-0 lg:left-0 lg:w-16 bg-[#111313] text-white border-r border-zinc-800 flex flex-row lg:flex-col items-center gap-2 p-2">
        <div className="relative">
          <button title="New request" onClick={() => setShowNewMenu((value) => !value)} className="h-11 w-11 rounded-[8px] bg-lime-300 text-zinc-950 flex items-center justify-center">
            <Plus size={20} />
          </button>
          {showNewMenu && (
            <div className="absolute left-0 top-14 z-50 w-64 rounded-[8px] border border-zinc-200 bg-white p-2 text-zinc-950 shadow-2xl lg:left-14 lg:top-0">
              <p className="px-2 py-2 text-xs font-semibold uppercase text-zinc-500">New</p>
              {tools.map((tool) => (
                <button key={tool.id} onClick={() => addProjectWithMode(tool.id)} className="flex w-full items-center gap-3 rounded-[8px] px-3 py-2.5 text-left text-sm hover:bg-zinc-100">
                  <tool.icon size={17} />
                  <span className="flex-1">{tool.label}</span>
                  <span className="text-[10px] text-zinc-500">{tool.status}</span>
                </button>
              ))}
            </div>
          )}
        </div>
        <button title="Projects" onClick={() => { setShowNewMenu(false); setActiveSection("projects"); }} className={cn("h-11 w-11 rounded-[8px] flex items-center justify-center", activeSection === "projects" ? "bg-lime-300 text-zinc-950" : "text-zinc-300 hover:bg-white/10")}>
          <Layers3 size={19} />
        </button>
        <button title="Settings" onClick={() => { setShowNewMenu(false); setActiveSection("settings"); }} className={cn("h-11 w-11 rounded-[8px] flex items-center justify-center", activeSection === "settings" ? "bg-lime-300 text-zinc-950" : "text-zinc-300 hover:bg-white/10")}>
          <Settings size={19} />
        </button>
        <button title="Workspace" onClick={() => { setShowNewMenu(false); setActiveSection("workspace"); }} className={cn("h-11 w-11 rounded-[8px] flex items-center justify-center lg:mt-auto", activeSection === "workspace" ? "bg-white text-zinc-950" : "text-zinc-300 hover:bg-white/10")}>
          <Wand2 size={19} />
        </button>
      </aside>

      <main className="lg:pl-16">
        <header className="min-h-20 bg-[#f6f7f3]/90 backdrop-blur border-b border-zinc-200 sticky top-0 z-20 px-4 lg:px-8 py-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-zinc-500">{tools.find((tool) => tool.id === project.mode)?.label}</p>
            <h1 className="text-2xl font-semibold tracking-tight">{project.title}</h1>
          </div>
          <div className="flex items-center gap-3">
            <StatePill state={project.state} />
            <button onClick={() => { setShowNewMenu(false); setShowChat(true); }} className="flex items-center gap-2 border border-zinc-300 bg-white text-zinc-800 rounded-[8px] px-4 py-2.5 text-sm font-semibold">
              <MessageSquareText size={17} />
              AI chat
            </button>
            <button onClick={() => { setShowNewMenu(false); setShowDesign(true); }} className="flex items-center gap-2 border border-zinc-300 bg-white text-zinc-800 rounded-[8px] px-4 py-2.5 text-sm font-semibold">
              <Paintbrush size={17} />
              Design brief
            </button>
            <button onClick={() => { setShowNewMenu(false); setShowPreview(true); }} className="flex items-center gap-2 border border-zinc-300 bg-white text-zinc-800 rounded-[8px] px-4 py-2.5 text-sm font-semibold">
              <FileText size={17} />
              Preview
            </button>
            <button onClick={handleBuild} disabled={!spec.fields.length || isWorking} className="flex items-center gap-2 bg-zinc-950 text-white rounded-[8px] px-4 py-2.5 text-sm font-semibold disabled:opacity-40">
              {isWorking && project.state === "building" ? <Loader2 className="animate-spin" size={17} /> : <Download size={17} />}
              Generate SM8F
            </button>
          </div>
        </header>

        {activeSection === "workspace" && (
          <Workspace
            project={project}
            spec={spec}
            prompt={prompt}
            setPrompt={setPrompt}
            attachments={attachments}
            setAttachments={setAttachments}
            onFiles={handleFiles}
            onGenerate={handleGenerate}
            onLoadCodexResponse={handleLoadCodexResponse}
            isWorking={isWorking}
            hasOpenAiKey={hasOpenAiKey}
            error={error}
            updateSpec={updateSpec}
            fieldCounts={fieldCounts}
          />
        )}
        {activeSection === "projects" && (
          <Projects
            projects={projects}
            activeProjectId={project.id}
            openProject={(projectId) => {
              setActiveProjectId(projectId);
              setActiveSection("workspace");
              setShowNewMenu(false);
            }}
          />
        )}
        {activeSection === "settings" && <SettingsPanel hasOpenAiKey={hasOpenAiKey} onStatusChange={setHasOpenAiKey} />}
        {showChat && (
          <ChatModal
            project={project}
            prompt={prompt}
            setPrompt={setPrompt}
            attachments={attachments}
            setAttachments={setAttachments}
            onFiles={handleFiles}
            onGenerate={handleGenerate}
            onLoadCodexResponse={handleLoadCodexResponse}
            isWorking={isWorking}
            hasOpenAiKey={hasOpenAiKey}
            error={error}
            onClose={() => setShowChat(false)}
          />
        )}
        {showDesign && (
          <DesignBriefModal
            design={project.designSettings}
            updateDesign={updateDesign}
            onLogo={async (files) => {
              const file = files?.[0];
              if (!file) return;
              const logo = await fileToAttachment(file);
              updateDesign({ ...project.designSettings, logo });
            }}
            onClose={() => setShowDesign(false)}
          />
        )}
        {showPreview && <PreviewModal spec={spec} updateSpec={updateSpec} onClose={() => setShowPreview(false)} />}
      </main>
    </div>
  );
}

function StatePill({ state }: { state: GenerationState }) {
  const labels: Record<GenerationState, string> = {
    idle: "Ready",
    draft: "Drafting",
    needsClarification: "Needs review",
    approved: "Approved",
    building: "Building",
    ready: "SM8F ready",
    error: "Error",
  };
  return <span className="rounded-full border border-zinc-300 bg-white px-3 py-1 text-xs font-semibold text-zinc-600">{labels[state]}</span>;
}

function Workspace(props: {
  project: ProjectRecord;
  spec: FormSpec;
  prompt: string;
  setPrompt: (value: string) => void;
  attachments: AttachmentPayload[];
  setAttachments: React.Dispatch<React.SetStateAction<AttachmentPayload[]>>;
  onFiles: (files: FileList | null) => void;
  onGenerate: () => void;
  onLoadCodexResponse: () => void;
  isWorking: boolean;
  hasOpenAiKey: boolean;
  error: string;
  updateSpec: (spec: FormSpec) => void;
  fieldCounts: { total: number; required: number; conditional: number; photos: number };
}) {
  return (
    <div className="min-h-[calc(100vh-5rem)] p-4 lg:p-6">
      <section className="space-y-5 min-w-0">
        <Metrics counts={props.fieldCounts} />
        <SpecEditor spec={props.spec} updateSpec={props.updateSpec} />
      </section>
    </div>
  );
}

function ChatModal(props: {
  project: ProjectRecord;
  prompt: string;
  setPrompt: (value: string) => void;
  attachments: AttachmentPayload[];
  setAttachments: React.Dispatch<React.SetStateAction<AttachmentPayload[]>>;
  onFiles: (files: FileList | null) => void;
  onGenerate: () => void;
  onLoadCodexResponse: () => void;
  isWorking: boolean;
  hasOpenAiKey: boolean;
  error: string;
  onClose: () => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-zinc-950/55 p-3 lg:p-6">
      <section className="flex h-[86vh] w-full max-w-5xl flex-col rounded-[8px] border border-zinc-200 bg-white shadow-2xl">
        <div className="border-b border-zinc-200 flex items-center justify-between gap-3 p-4">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center">
              <MessageSquareText size={18} />
            </div>
            <div>
              <h2 className="font-semibold">AI chat</h2>
              <p className="text-xs text-zinc-500">Describe, revise, approve</p>
            </div>
          </div>
          <button onClick={props.onClose} className="h-9 w-9 rounded-[8px] border border-zinc-300 bg-white text-zinc-700 flex items-center justify-center hover:bg-zinc-100" aria-label="Close AI chat">
            <X size={18} />
          </button>
        </div>
        {!props.hasOpenAiKey && (
          <div className="mx-4 mt-4 rounded-[8px] border border-lime-200 bg-lime-50 p-3 text-sm text-zinc-700 space-y-2">
            <p>Codex local bridge is active. This app writes request files for Codex instead of generating fake AI fields.</p>
            {props.project.codexRequestId && (
              <div className="space-y-2">
                <p className="font-mono text-xs break-all">Response: {props.project.codexResponsePath}</p>
                <button onClick={props.onLoadCodexResponse} disabled={props.isWorking} className="rounded-[8px] bg-zinc-950 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">
                  Load Codex response
                </button>
              </div>
            )}
          </div>
        )}
        <div className="flex-1 overflow-auto px-4 py-4 space-y-4">
          {props.project.messages.map((message) => (
            <div key={message.id} className={cn("rounded-[8px] p-4 text-sm whitespace-pre-wrap", message.role === "user" ? "bg-zinc-950 text-white" : "bg-[#f4f5ef] text-zinc-800")}>
              <div className="flex items-center gap-2 mb-2 text-xs opacity-70">
                {message.role === "user" ? <MessageSquareText size={14} /> : <Bot size={14} />}
                {message.role}
              </div>
              {message.content}
              {!!message.attachments?.length && (
                <div className="mt-3 flex flex-wrap gap-2">
                  {message.attachments.map((file) => (
                    <span key={file.id}>
                      <FileChip file={file} />
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="p-4 border-t border-zinc-200 space-y-3">
          <textarea
            value={props.prompt}
            onChange={(event) => props.setPrompt(event.target.value)}
            className="w-full h-28 resize-none rounded-[8px] border border-zinc-300 p-3 text-sm outline-none focus:border-zinc-950"
            placeholder={props.project.mode === "create_from_prompt" ? "Describe the form scope, required questions, answer types, conditional logic, and any preferred design style..." : "Ask Autoform to inspect a PDF, build a form, add conditional logic, or revise the current spec..."}
          />
          <div className="flex flex-wrap gap-2">
            {props.attachments.map((file) => (
              <button key={file.id} onClick={() => props.setAttachments((current) => current.filter((item) => item.id !== file.id))}>
                <FileChip file={file} />
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2">
            <label className="flex items-center gap-2 border border-zinc-300 rounded-[8px] px-3 py-2 text-sm cursor-pointer bg-white">
              <Upload size={16} />
              Upload files
              <input className="hidden" type="file" multiple accept=".pdf,.docx,.sm8f,.json,.png,.jpg,.jpeg,.txt,.md" onChange={(event) => props.onFiles(event.target.files)} />
            </label>
            <button onClick={props.onGenerate} disabled={props.isWorking || (!props.prompt.trim() && !props.attachments.length)} className="flex-1 bg-lime-300 text-zinc-950 rounded-[8px] px-4 py-2 text-sm font-semibold disabled:opacity-50">
              {props.isWorking ? "Working..." : props.hasOpenAiKey ? (props.project.spec.fields.length ? "Revise plan" : "Generate plan") : "Prepare Codex brief"}
            </button>
          </div>
          {props.error && <p className="text-sm text-red-600">{props.error}</p>}
        </div>
      </section>
    </div>
  );
}

function PanelTitle({ icon: Icon, title, subtitle }: { icon: React.ElementType; title: string; subtitle: string }) {
  return (
    <div className="p-4 border-b border-zinc-200 flex items-center gap-3">
      <div className="h-9 w-9 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center">
        <Icon size={18} />
      </div>
      <div>
        <h2 className="font-semibold">{title}</h2>
        <p className="text-xs text-zinc-500">{subtitle}</p>
      </div>
    </div>
  );
}

function FileChip({ file }: { file: AttachmentPayload }) {
  return (
    <span className="inline-flex items-center gap-1 rounded-[6px] border border-zinc-300 bg-white px-2 py-1 text-xs text-zinc-700">
      <FileText size={13} />
      {file.name}
    </span>
  );
}

function Metrics({ counts }: { counts: { total: number; required: number; conditional: number; photos: number } }) {
  return (
    <div className="grid grid-cols-4 gap-3">
      {[
        ["Fields", counts.total],
        ["Required", counts.required],
        ["Logic", counts.conditional],
        ["Photos", counts.photos],
      ].map(([label, value]) => (
        <div key={label} className="bg-white border border-zinc-200 rounded-[8px] p-4">
          <p className="text-xs text-zinc-500">{label}</p>
          <p className="text-2xl font-semibold">{value}</p>
        </div>
      ))}
    </div>
  );
}

function SpecEditor({ spec, updateSpec }: { spec: FormSpec; updateSpec: (spec: FormSpec) => void }) {
  const [optionsIndex, setOptionsIndex] = useState<number | null>(null);
  const [detailsIndex, setDetailsIndex] = useState<number | null>(null);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);
  const updateField = (index: number, patch: Partial<ServiceM8Field>) => {
    const fields = spec.fields.map((field, fieldIndex) => (fieldIndex === index ? { ...field, ...patch } : field));
    updateSpec({ ...spec, fields });
  };

  const orderedFields = (fields: ServiceM8Field[]) =>
    fields.map((field, index) => ({ ...field, sortOrder: index + 1 }));

  const reorderFields = (fromIndex: number, toIndex: number) => {
    if (fromIndex === toIndex || fromIndex < 0 || toIndex < 0) return;
    const fields = [...spec.fields];
    const [moved] = fields.splice(fromIndex, 1);
    fields.splice(toIndex, 0, moved);
    updateSpec({ ...spec, fields: orderedFields(fields) });
  };

  const addField = () => {
    updateSpec({
      ...spec,
      fields: [
        ...spec.fields,
        { label: "New Question", type: "text", required: false, additionalDetails: "", sortOrder: spec.fields.length + 1 },
      ],
    });
  };

  return (
    <div className="bg-white border border-zinc-200 rounded-[8px] overflow-hidden">
      <PanelTitle icon={TableProperties} title="Editable form spec" subtitle="Fields, options, required states and skip logic" />
      <div className="p-4 grid grid-cols-3 gap-3 border-b border-zinc-200">
        <TextInput label="Title" value={spec.title} onChange={(title) => updateSpec({ ...spec, title })} />
        <TextInput label="Badge" value={spec.badgeName} onChange={(badgeName) => updateSpec({ ...spec, badgeName: cleanBadge(badgeName) })} />
        <TextInput label="Description" value={spec.description} onChange={(description) => updateSpec({ ...spec, description })} />
      </div>
      <div className="overflow-auto max-h-[56vh]">
        <table className="w-full table-fixed text-sm">
          <colgroup>
            <col className="w-[40px]" />
            <col className="w-[34%]" />
            <col className="w-[120px]" />
            <col className="w-[120px]" />
            <col className="w-[56px]" />
            <col className="w-[380px]" />
          </colgroup>
          <thead className="sticky top-0 bg-zinc-950 text-white">
            <tr>
              <th className="p-2" aria-label="Reorder" />
              <th className="text-left p-2 font-medium">Question</th>
              <th className="text-left p-2 font-medium">Type</th>
              <th className="text-left p-2 font-medium">Options</th>
              <th className="text-left p-2 font-medium">Req</th>
              <th className="text-left p-2 font-medium">Condition</th>
            </tr>
          </thead>
          <tbody>
            {spec.fields.map((field, index) => (
              <tr
                key={`${field.label}-${field.sortOrder}-${index}`}
                onDragOver={(event) => {
                  if (draggedIndex === null || draggedIndex === index) return;
                  event.preventDefault();
                  setDragOverIndex(index);
                }}
                onDragLeave={() => setDragOverIndex(null)}
                onDrop={(event) => {
                  event.preventDefault();
                  if (draggedIndex !== null) reorderFields(draggedIndex, index);
                  setDraggedIndex(null);
                  setDragOverIndex(null);
                }}
                className={cn(
                  "border-b border-zinc-200 align-top transition-colors",
                  draggedIndex === index && "opacity-45",
                  dragOverIndex === index && draggedIndex !== index && "bg-lime-50",
                )}
              >
                <td className="p-2 text-center">
                  <button
                    draggable
                    onDragStart={(event) => {
                      setDraggedIndex(index);
                      event.dataTransfer.effectAllowed = "move";
                      event.dataTransfer.setData("text/plain", String(index));
                    }}
                    onDragEnd={() => {
                      setDraggedIndex(null);
                      setDragOverIndex(null);
                    }}
                    className="inline-flex h-8 w-7 cursor-grab items-center justify-center rounded border border-transparent text-zinc-400 hover:border-zinc-200 hover:bg-zinc-50 hover:text-zinc-700 active:cursor-grabbing"
                    title="Drag to reorder"
                    aria-label={`Drag ${field.label} to reorder`}
                  >
                    <GripVertical size={16} />
                  </button>
                </td>
                <td className="p-2">
                  <div className="flex items-center gap-1">
                    <input className="min-w-0 flex-1 rounded border border-zinc-200 px-2 py-1" value={field.label} onChange={(event) => updateField(index, { label: event.target.value })} />
                    <button
                      onClick={() => setDetailsIndex(index)}
                      className={cn("flex h-8 w-8 shrink-0 items-center justify-center rounded border text-zinc-600 hover:bg-zinc-50", field.additionalDetails ? "border-lime-300 bg-lime-50" : "border-zinc-200")}
                      title={field.additionalDetails ? "Edit guidance" : "Add guidance"}
                      aria-label={field.additionalDetails ? `Edit guidance for ${field.label}` : `Add guidance for ${field.label}`}
                    >
                      <Pencil size={14} />
                    </button>
                  </div>
                </td>
                <td className="p-2">
                  <select className="w-full rounded border border-zinc-200 px-2 py-1" value={field.type} onChange={(event) => updateField(index, { type: event.target.value as ServiceM8Field["type"] })}>
                    {["text", "textarea", "number", "date", "time", "select", "checkbox", "multi_answer", "photo", "signature"].map((type) => <option key={type}>{type}</option>)}
                  </select>
                </td>
                <td className="p-2">
                  <button onClick={() => setOptionsIndex(index)} className="inline-flex w-full items-center justify-center gap-1 rounded border border-zinc-200 px-2 py-1 text-xs text-zinc-700 hover:bg-zinc-50">
                    <Pencil size={12} />
                    <span className="truncate">{(field.options || []).length ? `${field.options?.length} options` : "Options"}</span>
                  </button>
                </td>
                <td className="p-2 text-center">
                  <input type="checkbox" checked={field.required} onChange={(event) => updateField(index, { required: event.target.checked })} />
                </td>
                <td className="p-2">
                  <ConditionEditor fields={spec.fields} currentIndex={index} condition={field.conditions?.[0]} onChange={(condition) => updateField(index, { conditions: condition.questionLabel ? [condition] : [] })} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <button onClick={addField} className="m-4 flex items-center gap-2 rounded-[8px] border border-zinc-300 px-3 py-2 text-sm">
        <Plus size={16} />
        Add field
      </button>
      {optionsIndex !== null && (
        <OptionsModal
          field={spec.fields[optionsIndex]}
          onClose={() => setOptionsIndex(null)}
          onSave={(options) => {
            updateField(optionsIndex, { options });
            setOptionsIndex(null);
          }}
        />
      )}
      {detailsIndex !== null && (
        <DetailsModal
          field={spec.fields[detailsIndex]}
          onClose={() => setDetailsIndex(null)}
          onSave={(additionalDetails) => {
            updateField(detailsIndex, { additionalDetails });
            setDetailsIndex(null);
          }}
        />
      )}
    </div>
  );
}

const operatorOptions: { value: FieldCondition["operator"]; label: string }[] = [
  { value: "EQ", label: "Equals" },
  { value: "NEQ", label: "Does not equal" },
  { value: "CON", label: "Contains" },
  { value: "NCON", label: "Does not contain" },
  { value: "LT", label: "Less than" },
  { value: "GT", label: "Greater than" },
  { value: "LTE", label: "Less than or equal" },
  { value: "GTE", label: "Greater than or equal" },
];

function ConditionEditor({ fields, currentIndex = -1, condition, onChange }: { fields: ServiceM8Field[]; currentIndex?: number; condition?: FieldCondition; onChange: (condition: FieldCondition) => void }) {
  const value = condition || { questionLabel: "", operator: "EQ", value: "" };
  const availableFields = fields.filter((_, index) => index !== currentIndex);
  const selectedField = availableFields.find((field) => field.label === value.questionLabel);
  const options = selectedField?.options || [];
  const useCustomValue = !!options.length && (!!value.value && !options.includes(value.value));
  return (
    <div className="grid max-w-[360px] grid-cols-[130px_104px_120px] gap-1">
      <select
        className="min-w-0 rounded border border-zinc-200 px-2 py-1 text-xs"
        value={value.questionLabel}
        onChange={(event) => onChange({ ...value, questionLabel: event.target.value, value: "" })}
      >
        <option value="">No condition</option>
        {availableFields.map((field) => <option key={field.label} value={field.label}>{field.label}</option>)}
      </select>
      <select className="min-w-0 rounded border border-zinc-200 px-1 py-1 text-xs" value={value.operator} onChange={(event) => onChange({ ...value, operator: event.target.value as FieldCondition["operator"] })}>
        {operatorOptions.map((operator) => <option key={operator.value} value={operator.value}>{operator.label}</option>)}
      </select>
      {options.length && !useCustomValue ? (
        <select className="min-w-0 rounded border border-zinc-200 px-2 py-1 text-xs" value={value.value} onChange={(event) => onChange({ ...value, value: event.target.value === "__other__" ? "__other__" : event.target.value })}>
          <option value="">Select value</option>
          {options.map((option) => <option key={option} value={option}>{option}</option>)}
          <option value="__other__">Other...</option>
        </select>
      ) : (
        <input className="min-w-0 rounded border border-zinc-200 px-2 py-1 text-xs" placeholder={options.length ? "Other value" : "Value"} value={value.value === "__other__" ? "" : value.value} onChange={(event) => onChange({ ...value, value: event.target.value })} />
      )}
    </div>
  );
}

function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}
      <input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-[8px] border border-zinc-300 px-3 py-2 text-sm text-zinc-900" />
    </label>
  );
}

function OptionsModal({ field, onSave, onClose }: { field: ServiceM8Field; onSave: (options: string[]) => void; onClose: () => void }) {
  const [options, setOptions] = useState<string[]>(() => {
    const existing = field.options?.length ? field.options : [""];
    return [...existing, ...Array(Math.max(0, 15 - existing.length)).fill("")].slice(0, 15);
  });

  const updateOption = (index: number, value: string) => {
    setOptions((current) => current.map((option, optionIndex) => optionIndex === index ? value : option));
  };

  return (
    <div className="fixed inset-0 z-[90] bg-zinc-950/50 p-4" role="dialog" aria-modal="true">
      <div className="mx-auto mt-8 max-w-xl rounded-[8px] bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-zinc-200 p-4">
          <div>
            <h2 className="text-lg font-semibold">Edit options</h2>
            <p className="text-sm text-zinc-500">{field.label} · up to 15 options</p>
          </div>
          <button onClick={onClose} className="rounded-[8px] border border-zinc-300 px-3 py-2 text-sm">Close</button>
        </div>
        <div className="grid max-h-[70vh] grid-cols-1 gap-2 overflow-auto p-4 sm:grid-cols-2">
          {options.map((option, index) => (
            <label key={index} className="flex items-center gap-2 text-xs text-zinc-500">
              <span className="w-14 shrink-0">Option {index + 1}</span>
              <input value={option} onChange={(event) => updateOption(index, event.target.value)} className="min-w-0 flex-1 rounded-[8px] border border-zinc-300 px-2 py-1.5 text-sm text-zinc-900" />
            </label>
          ))}
        </div>
        <div className="flex justify-end gap-2 border-t border-zinc-200 p-4">
          <button onClick={onClose} className="rounded-[8px] border border-zinc-300 px-4 py-2 text-sm">Cancel</button>
          <button onClick={() => onSave(options.map((option) => option.trim()).filter(Boolean))} className="rounded-[8px] bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save options</button>
        </div>
      </div>
    </div>
  );
}

function DetailsModal({ field, onSave, onClose }: { field: ServiceM8Field; onSave: (value: string) => void; onClose: () => void }) {
  const [value, setValue] = useState(field.additionalDetails || "");
  return (
    <div className="fixed inset-0 z-[90] bg-zinc-950/50 p-4" role="dialog" aria-modal="true">
      <div className="mx-auto mt-12 max-w-2xl rounded-[8px] bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-zinc-200 p-4">
          <div>
            <h2 className="text-lg font-semibold">Edit guidance</h2>
            <p className="text-sm text-zinc-500">{field.label}</p>
          </div>
          <button onClick={onClose} className="rounded-[8px] border border-zinc-300 px-3 py-2 text-sm">Close</button>
        </div>
        <div className="p-4">
          <textarea value={value} onChange={(event) => setValue(event.target.value)} className="h-56 w-full resize-none rounded-[8px] border border-zinc-300 p-3 text-sm text-zinc-900" placeholder="Add guidance, prompt text, hints, or technician instructions. Use one line per instruction if helpful." />
        </div>
        <div className="flex justify-end gap-2 border-t border-zinc-200 p-4">
          <button onClick={onClose} className="rounded-[8px] border border-zinc-300 px-4 py-2 text-sm">Cancel</button>
          <button onClick={() => onSave(value)} className="rounded-[8px] bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save guidance</button>
        </div>
      </div>
    </div>
  );
}

function OutputPanel({ spec, onBuild, disabled }: { spec: FormSpec; onBuild: () => void; disabled: boolean }) {
  return (
    <div className="bg-zinc-950 text-white rounded-[8px] p-5">
      <div className="flex items-center gap-3">
        <Box className="text-lime-300" />
        <div>
          <h2 className="font-semibold">SM8F package</h2>
          <p className="text-xs text-zinc-400">ZIP archive with form.json and template.docx</p>
        </div>
      </div>
      <button onClick={onBuild} disabled={disabled} className="mt-5 w-full bg-lime-300 text-zinc-950 rounded-[8px] py-3 text-sm font-semibold disabled:opacity-40">
        Build downloadable .sm8f
      </button>
      <p className="mt-4 text-xs text-zinc-400">Badge: {spec.badgeName || "Unset"} · Fields: {spec.fields.length}</p>
    </div>
  );
}

function sectionDisplayConditions(section: FormSpec["docxContent"]["sections"][number]) {
  if (Array.isArray(section.displayWhen)) return section.displayWhen;
  if (section.displayWhen) return [section.displayWhen];
  if (Array.isArray(section.conditions)) return section.conditions;
  return [];
}

function PreviewPanel({ spec, updateSpec }: { spec: FormSpec; updateSpec?: (spec: FormSpec) => void }) {
  const updateSectionCondition = (index: number, condition: FieldCondition) => {
    if (!updateSpec) return;
    const sections = spec.docxContent.sections.map((section, sectionIndex) => {
      if (sectionIndex !== index) return section;
      const displayWhen = condition.questionLabel ? [condition] : [];
      return { ...section, displayWhen, conditions: displayWhen };
    });
    updateSpec({ ...spec, docxContent: { ...spec.docxContent, sections } });
  };

  return (
    <div className="bg-white border border-zinc-200 rounded-[8px] p-4">
      <PanelTitle icon={FileText} title="Report preview" subtitle="Structure and document sections" />
      <div className="mt-4 space-y-3 max-h-[52vh] overflow-auto">
        {spec.docxContent.sections.length ? spec.docxContent.sections.map((section, index) => (
          <div key={section.title} className="border border-zinc-200 rounded-[8px] overflow-hidden">
            <div className="flex items-center justify-between gap-3 bg-zinc-800 px-3 py-2 text-sm font-semibold text-white">
              <span>{section.title}</span>
              {sectionDisplayConditions(section).length > 0 && <span className="rounded bg-lime-300 px-2 py-0.5 text-[11px] font-semibold text-zinc-950">Hidden by IF</span>}
            </div>
            {updateSpec && (
              <div className="border-b border-zinc-200 bg-zinc-50 px-3 py-2">
                <div className="flex flex-wrap items-center gap-2 text-xs text-zinc-500">
                  <span className="font-semibold text-zinc-700">Show section when</span>
                  <ConditionEditor
                    fields={spec.fields}
                    condition={sectionDisplayConditions(section)[0]}
                    onChange={(condition) => updateSectionCondition(index, condition)}
                  />
                </div>
              </div>
            )}
            <pre className="p-3 text-xs whitespace-pre-wrap font-sans text-zinc-600">{section.content || "No content yet"}</pre>
          </div>
        )) : <p className="text-sm text-zinc-500">Generate a plan to preview DOCX sections.</p>}
      </div>
    </div>
  );
}

function PreviewModal({ spec, updateSpec, onClose }: { spec: FormSpec; updateSpec: (spec: FormSpec) => void; onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-[80] bg-zinc-950/50 p-4 lg:p-8" role="dialog" aria-modal="true">
      <div className="mx-auto flex h-full max-w-5xl flex-col rounded-[8px] bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-zinc-200 p-4">
          <div>
            <h2 className="text-lg font-semibold">Report preview</h2>
            <p className="text-sm text-zinc-500">DOCX sections and merge-field output structure</p>
          </div>
          <button onClick={onClose} className="rounded-[8px] border border-zinc-300 px-3 py-2 text-sm font-semibold">Close</button>
        </div>
        <div className="min-h-0 flex-1 overflow-auto p-5">
          <PreviewPanel spec={spec} updateSpec={updateSpec} />
        </div>
      </div>
    </div>
  );
}

function DesignBriefModal({ design, updateDesign, onLogo, onClose }: { design: DesignSettings; updateDesign: (design: DesignSettings) => void; onLogo: (files: FileList | null) => void; onClose: () => void }) {
  const update = (patch: Partial<DesignSettings>) => updateDesign({ ...design, ...patch });
  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center bg-zinc-950/55 p-3 lg:p-6" role="dialog" aria-modal="true">
      <div className="flex max-h-[86vh] w-full max-w-3xl flex-col rounded-[8px] bg-white shadow-2xl">
        <div className="flex items-center justify-between border-b border-zinc-200 p-4">
          <div className="flex items-center gap-3">
            <div className="h-9 w-9 rounded-[8px] bg-zinc-950 text-lime-300 flex items-center justify-center">
              <Paintbrush size={18} />
            </div>
            <div>
              <h2 className="font-semibold">Design brief</h2>
              <p className="text-xs text-zinc-500">Included in the AI form spec</p>
            </div>
          </div>
          <button onClick={onClose} className="h-9 w-9 rounded-[8px] border border-zinc-300 bg-white text-zinc-700 flex items-center justify-center hover:bg-zinc-100" aria-label="Close design brief">
            <X size={18} />
          </button>
        </div>
        <div className="min-h-0 flex-1 space-y-3 overflow-auto p-4">
          <label className="flex items-center justify-between gap-3 rounded-[8px] border border-zinc-200 px-3 py-2 text-sm text-zinc-700">
            Let AI choose design elements
            <input type="checkbox" checked={!!design.aiChooseDesign} onChange={(event) => update({ aiChooseDesign: event.target.checked })} className="h-4 w-4 accent-lime-400" />
          </label>
          <Select
            label="Style direction"
            value={design.stylePreset || "ai"}
            onChange={(stylePreset) => update({ stylePreset: stylePreset as DesignSettings["stylePreset"] })}
            options={["ai", "clean_trade", "corporate", "source_replica", "minimal"]}
          />
          <label className="text-xs text-zinc-500">
            Design instructions for AI
            <textarea
              value={design.designBrief || ""}
              onChange={(event) => update({ designBrief: event.target.value })}
              className="mt-1 h-28 w-full resize-none rounded-[8px] border border-zinc-300 p-3 text-sm text-zinc-900"
              placeholder="Example: match our brand colours, use editable tables, formal compliance-report style..."
            />
          </label>
          <div className="grid grid-cols-2 gap-3">
            <label className="text-xs text-zinc-500">
              Primary
              <input type="color" value={design.primaryColor} onChange={(event) => update({ primaryColor: event.target.value })} className="mt-1 h-9 w-full rounded border border-zinc-300" />
            </label>
            <label className="text-xs text-zinc-500">
              Accent
              <input type="color" value={design.accentColor} onChange={(event) => update({ accentColor: event.target.value })} className="mt-1 h-9 w-full rounded border border-zinc-300" />
            </label>
          </div>
          <label className="flex items-center gap-2 rounded-[8px] border border-dashed border-zinc-300 px-3 py-2 text-sm text-zinc-700 cursor-pointer">
            <Image size={16} />
            Upload logo
            <input className="hidden" type="file" accept=".png,.jpg,.jpeg" onChange={(event) => onLogo(event.target.files)} />
          </label>
          {design.logo && <p className="text-xs text-zinc-500">{design.logo.name}</p>}
        </div>
        <div className="flex justify-end border-t border-zinc-200 p-4">
          <button onClick={onClose} className="rounded-[8px] bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Done</button>
        </div>
      </div>
    </div>
  );
}

function InlineDesignPanel({ design, updateDesign, onLogo }: { design: DesignSettings; updateDesign: (design: DesignSettings) => void; onLogo: (files: FileList | null) => void }) {
  const update = (patch: Partial<DesignSettings>) => updateDesign({ ...design, ...patch });
  return (
    <div className="bg-white border border-zinc-200 rounded-[8px] p-4">
      <PanelTitle icon={Paintbrush} title="Design brief" subtitle="Included in the AI form spec" />
      <div className="mt-4 space-y-3">
        <label className="flex items-center justify-between gap-3 rounded-[8px] border border-zinc-200 px-3 py-2 text-sm text-zinc-700">
          Let AI choose design elements
          <input type="checkbox" checked={!!design.aiChooseDesign} onChange={(event) => update({ aiChooseDesign: event.target.checked })} className="h-4 w-4 accent-lime-400" />
        </label>
        <Select
          label="Style direction"
          value={design.stylePreset || "ai"}
          onChange={(stylePreset) => update({ stylePreset: stylePreset as DesignSettings["stylePreset"] })}
          options={["ai", "clean_trade", "corporate", "source_replica", "minimal"]}
        />
        <label className="text-xs text-zinc-500">
          Design instructions for AI
          <textarea
            value={design.designBrief || ""}
            onChange={(event) => update({ designBrief: event.target.value })}
            className="mt-1 h-24 w-full resize-none rounded-[8px] border border-zinc-300 p-3 text-sm text-zinc-900"
            placeholder="Example: match our brand colours, use editable tables, formal compliance-report style..."
          />
        </label>
        <div className="grid grid-cols-2 gap-3">
          <label className="text-xs text-zinc-500">
            Primary
            <input type="color" value={design.primaryColor} onChange={(event) => update({ primaryColor: event.target.value })} className="mt-1 h-9 w-full rounded border border-zinc-300" />
          </label>
          <label className="text-xs text-zinc-500">
            Accent
            <input type="color" value={design.accentColor} onChange={(event) => update({ accentColor: event.target.value })} className="mt-1 h-9 w-full rounded border border-zinc-300" />
          </label>
        </div>
        <label className="flex items-center gap-2 rounded-[8px] border border-dashed border-zinc-300 px-3 py-2 text-sm text-zinc-700 cursor-pointer">
          <Image size={16} />
          Upload logo
          <input className="hidden" type="file" accept=".png,.jpg,.jpeg" onChange={(event) => onLogo(event.target.files)} />
        </label>
        {design.logo && <p className="text-xs text-zinc-500">{design.logo.name}</p>}
      </div>
    </div>
  );
}

function DesignStudio({ design, updateDesign, onLogo }: { design: DesignSettings; updateDesign: (design: DesignSettings) => void; onLogo: (files: FileList | null) => void }) {
  const update = (patch: Partial<DesignSettings>) => updateDesign({ ...design, ...patch });
  return (
    <div className="p-4 lg:p-6 grid grid-cols-1 xl:grid-cols-[1fr_420px] gap-6">
      <section className="bg-white border border-zinc-200 rounded-[8px] p-6">
        <PanelTitle icon={Paintbrush} title="Full style editor" subtitle="Brand, typography, table and document controls" />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
          <TextInput label="Company name" value={design.companyName} onChange={(companyName) => update({ companyName })} />
          <TextInput label="Header text" value={design.headerText} onChange={(headerText) => update({ headerText })} />
          <TextInput label="Footer text" value={design.footerText} onChange={(footerText) => update({ footerText })} />
          <label className="text-xs text-zinc-500">
            Logo upload
            <span className="mt-1 flex items-center gap-2 rounded-[8px] border border-dashed border-zinc-300 px-3 py-2 text-sm text-zinc-700 cursor-pointer">
              <Image size={16} />
              Upload logo
              <input className="hidden" type="file" accept=".png,.jpg,.jpeg" onChange={(event) => onLogo(event.target.files)} />
            </span>
            {design.logo && <span className="mt-1 block text-[11px] text-zinc-500">{design.logo.name}</span>}
          </label>
          {[
            ["Primary", "primaryColor"],
            ["Accent", "accentColor"],
            ["Header", "headerColor"],
            ["Footer", "footerColor"],
            ["Table header", "tableHeaderColor"],
            ["Table border", "tableBorderColor"],
          ].map(([label, key]) => (
            <label key={key} className="text-xs text-zinc-500">
              {label}
              <input type="color" value={(design as any)[key]} onChange={(event) => update({ [key]: event.target.value } as any)} className="mt-1 h-10 w-full rounded border border-zinc-300" />
            </label>
          ))}
          <Select label="Font" value={design.fontFamily} onChange={(fontFamily) => update({ fontFamily: fontFamily as DesignSettings["fontFamily"] })} options={["Arial", "Calibri", "Inter", "Aptos"]} />
          <Select label="Heading style" value={design.headingStyle} onChange={(headingStyle) => update({ headingStyle: headingStyle as DesignSettings["headingStyle"] })} options={["bar", "underline", "boxed"]} />
          <Select label="Table style" value={design.tableStyle} onChange={(tableStyle) => update({ tableStyle: tableStyle as DesignSettings["tableStyle"] })} options={["source", "minimal", "grid"]} />
          <Select label="Logo placement" value={design.logoPlacement} onChange={(logoPlacement) => update({ logoPlacement: logoPlacement as DesignSettings["logoPlacement"] })} options={["left", "center", "right"]} />
          <Range label="Body font size" value={design.bodyFontSize} min={8} max={14} onChange={(bodyFontSize) => update({ bodyFontSize })} />
          <Range label="Page margin" value={design.pageMargin} min={360} max={1440} onChange={(pageMargin) => update({ pageMargin })} />
          <Range label="Logo width" value={design.logoWidth} min={80} max={280} onChange={(logoWidth) => update({ logoWidth })} />
        </div>
      </section>
      <section className="rounded-[8px] border border-zinc-200 bg-white p-5">
        <div className="aspect-[3/4] bg-[#fbfbf8] border border-zinc-300 p-8 shadow-xl">
          <div style={{ background: design.headerColor }} className="h-14 text-white flex items-center px-4 font-semibold">
            {design.companyName}
          </div>
          <div className="mt-5" style={{ color: design.primaryColor }}>
            <h3 className="text-2xl font-semibold">Report heading</h3>
            <p className="mt-2 text-sm text-zinc-500">{design.headerText}</p>
          </div>
          <div className="mt-6 border" style={{ borderColor: design.tableBorderColor }}>
            <div className="px-3 py-2 text-white text-sm font-semibold" style={{ background: design.tableHeaderColor }}>Section</div>
            <div className="grid grid-cols-2 text-sm">
              <div className="p-3 border-r" style={{ borderColor: design.tableBorderColor }}>Question</div>
              <div className="p-3">Answer</div>
            </div>
          </div>
          <div className="mt-auto pt-10 text-xs" style={{ color: design.footerColor }}>{design.footerText}</div>
        </div>
      </section>
    </div>
  );
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}
      <select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-[8px] border border-zinc-300 px-3 py-2 text-sm text-zinc-900">
        {options.map((option) => <option key={option}>{option}</option>)}
      </select>
    </label>
  );
}

function Range({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) {
  return (
    <label className="text-xs text-zinc-500">
      {label}: {value}
      <input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full accent-lime-400" />
    </label>
  );
}

function Projects({ projects, activeProjectId, openProject }: { projects: ProjectRecord[]; activeProjectId: string; openProject: (id: string) => void }) {
  return (
    <div className="p-6">
      <div className="bg-white border border-zinc-200 rounded-[8px]">
        <PanelTitle icon={Layers3} title="Projects" subtitle="Local browser project history" />
        <div className="divide-y divide-zinc-200">
          {projects.map((project) => (
            <button key={project.id} onClick={() => openProject(project.id)} className={cn("w-full p-4 flex items-center justify-between text-left transition-colors hover:bg-zinc-50", activeProjectId === project.id && "bg-lime-50 hover:bg-lime-50")}>
              <div>
                <div className="flex items-center gap-2">
                  <p className="font-semibold">{project.title}</p>
                  {activeProjectId === project.id && <span className="rounded-full bg-lime-200 px-2 py-0.5 text-[10px] font-semibold uppercase text-zinc-800">Open</span>}
                </div>
                <p className="text-xs text-zinc-500">{project.mode} · {new Date(project.updatedAt).toLocaleString()}</p>
              </div>
              <span className="flex items-center gap-2 text-sm font-semibold text-zinc-500">
                Open
                <ChevronRight size={18} />
              </span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

function SettingsPanel({ hasOpenAiKey, onStatusChange }: { hasOpenAiKey: boolean; onStatusChange: (value: boolean) => void }) {
  const [apiKey, setApiKey] = useState("");
  const [message, setMessage] = useState("");
  const saveKey = async () => {
    const result = await saveOpenAiKey(apiKey);
    setMessage(result.message);
    onStatusChange(result.ok || hasOpenAiKey);
    if (result.ok) setApiKey("");
  };
  return (
    <div className="p-6">
      <div className="bg-white border border-zinc-200 rounded-[8px] p-6 max-w-2xl">
        <PanelTitle icon={Settings} title="Settings" subtitle="Environment and deployment checklist" />
        <div className="mt-6 space-y-4 text-sm text-zinc-600">
          <div className="rounded-[8px] border border-zinc-200 p-4">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="font-semibold text-zinc-900">OpenAI API key</p>
                <p className="text-xs text-zinc-500">{hasOpenAiKey ? "Configured for this server session." : "Not configured. Local Codex bridge will be used."}</p>
              </div>
              <span className={cn("rounded-full px-2 py-1 text-xs font-semibold", hasOpenAiKey ? "bg-lime-100 text-lime-800" : "bg-zinc-100 text-zinc-600")}>{hasOpenAiKey ? "Active" : "Local mode"}</span>
            </div>
            <div className="mt-4 flex gap-2">
              <input value={apiKey} onChange={(event) => setApiKey(event.target.value)} type="password" placeholder="sk-..." className="min-w-0 flex-1 rounded-[8px] border border-zinc-300 px-3 py-2 text-sm" />
              <button onClick={saveKey} className="rounded-[8px] bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save</button>
            </div>
            {message && <p className="mt-2 text-xs text-zinc-500">{message}</p>}
          </div>
          <p><Check className="inline mr-2 text-lime-600" size={16} />Locally, Save writes `OPENAI_API_KEY` to the git-ignored `.env` file.</p>
          <p><Check className="inline mr-2 text-lime-600" size={16} />For Vercel, store `OPENAI_API_KEY` in encrypted environment variables.</p>
          <p><Check className="inline mr-2 text-lime-600" size={16} />Set `APP_PASSWORD` for private admin access.</p>
          <p><Sparkles className="inline mr-2 text-blue-600" size={16} />Projects are saved to the local server DB now; Vercel Postgres is the likely production database later.</p>
        </div>
      </div>
    </div>
  );
}
